Implement API list and delete
wso2/product-microgateway pull request #1644
Opened 2021-02-18 05:20 UTC by SuKSW

### Purpose
Implementation to delete an API and to list existing APIs via the REST API, which will be done using apictl.
This PR was created after rebasing the original PR [here](https://github.com/wso2/product-microgateway/pull/1631)

### Issues
Fixes #1630 

### Automation tests
 - Unit tests added: Yes/No
 - Integration tests added: Yes/No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

2021-02-18 06:10 UTC, praminda requested changes

2021-02-18 06:10 UTC, praminda commented on adapter/pkg/xds/xds_server.go
> +func ListApis(apiType string, limitP *int64) *apiModel.APIMeta {
```suggestion
func ListApis(apiType string, limit *int64) *apiModel.APIMeta {
```

2021-02-18 06:10 UTC, praminda commented on adapter/resources/adapterAPI.yaml
> +        type: string
```suggestion
        type: string

```

2021-02-18 11:37 UTC, SuKSW commented on adapter/pkg/api/apis_impl.go
> +func extractAPIProject(payload []byte) (apiJsn []byte, swaggerJsn []byte, upstreamCerts []byte,
That'll reduce space for errors as well, adding a struct.

2021-02-18 12:27 UTC, SuKSW commented on adapter/pkg/api/apis_impl.go
> +func ApplyAPIProjectWithOverwrite(payload []byte, environments []string, overwriteP *bool) error {
Updating this to a meaningful name

2021-02-18 12:29 UTC, SuKSW commented on adapter/pkg/api/apis_impl.go
> +func DeleteAPI(apiName string, version string, vhostP *string) error {
Updating this to vhost

2021-02-18 12:29 UTC, SuKSW commented on adapter/pkg/api/apis_impl.go
> +func xdsUpdateAPI(name, version, apiType string, apiJsn, swaggerJsn, upstreamCerts []byte,
Renaming this

2021-02-18 12:30 UTC, SuKSW commented on adapter/pkg/api/apis_impl.go
> +func ListApis(apiTypeP *string, limitP *int64) *apiModel.APIMeta {
Adding meaningful names

2021-02-18 12:32 UTC, SuKSW commented on adapter/pkg/api/restserver/embedded_spec.go
> +    "/api": {
Updating this to /apis as discussed

2021-02-18 12:35 UTC, SuKSW commented on adapter/pkg/xds/xds_server.go
> +func ListApis(apiType string, limitP *int64) *apiModel.APIMeta {
Updating this

2021-02-18 12:36 UTC, SuKSW commented on adapter/resources/adapterAPI.yaml
> +        type: string
adding space at the end of file

2021-02-19 03:30 UTC, SuKSW commented on adapter/pkg/api/apis_impl.go
> +func extractAPIProject(payload []byte) (apiJsn []byte, swaggerJsn []byte, upstreamCerts []byte,
Using the name ProjectAPI to pass lint errors

2021-02-25 08:27 UTC, closed without merging

2021-02-25 08:27 UTC, SuKSW commented
Closing PR in order to resolve conflicts.